name: Artifacts
on:
  - pull_request
  - push
jobs:
  test:
    strategy:
      matrix:
        arch: [x86_64]
        os: [ubuntu, macos, windows]
      fail-fast: false
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0
      - run: |
          zig build test -Dtarget=${{matrix.os}}-${{matrix.arch}}
      - run: |
          zig build -Dtarget=${{matrix.os}}-${{matrix.arch}} -p zig-out-${{matrix.os}}-latest-${{matrix.arch}}
      - uses: actions/upload-artifact@v2
        with:
          name: zigup ${{ matrix.os }}-${{ matrix.arch }}
          path: zig-out/bin/*
      - if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: zigup ${{ matrix.os }}-aarch64
          path: zig-out-${{matrix.os}}-aarch64/bin/*
